import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { tree } from "../tree";
import styles from "../styles/Home.module.css";
import { TreeType } from "../types";
import documentImg from "../assets/document.jpg";
import folderImg from "../assets/folder.svg";
import arrowImg from "../assets/arrow.svg";

const Home: NextPage = () => {
  const onFolderHandler: React.MouseEventHandler<HTMLElement> = (e) => {
    if (!(e.target instanceof HTMLElement)) return;
    if (e.target.tagName === "IMG" && e.target.parentNode !== null) {
      e.target.parentNode.parentNode?.parentNode?.children[1].classList.toggle(
        "hidden"
      );
    }
  };

  const createTree = (data: TreeType) => {
    let children: JSX.Element[] = [];
    data.map((subData) => {
      if (typeof subData.children === "object") {
        children.push(
          <li key={subData.key} className="tree-group">
            <span onClick={onFolderHandler} className={styles.treeHeading}>
              <Image
                className={styles.treeGroupImg}
                width={10}
                height={10}
                src={arrowImg}
                alt="img"
              />

              <Image
                className={styles.treeHeadingImg}
                width={20}
                height={20}
                src={folderImg}
                alt="img"
              />
              {subData.title}
            </span>
            {createTree(subData.children)}
          </li>
        );
      } else {
        children.push(
          <span className={styles.treeFile} key={subData.key}>
            <Image
              className={styles.treeFileImg}
              width={20}
              height={20}
              src={documentImg}
              alt="img"
            />
            {subData.title}
          </span>
        );
      }
    });
    return (
      <ul style={{ marginLeft: "20px" }} className="tree-body">
        {children}
      </ul>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {createTree(tree)}
    </div>
  );
};

export default Home;
